31608181
Runtime Error _bulk in inline (ie request)
<p>I am learning this great tool ElasticSearch.</p>&#xA;&#xA;<p>Everything is in order:</p>&#xA;&#xA;<p>1) executes the query:</p>&#xA;&#xA;<pre><code>$ curl -XGET 'localhost:9200/website/blog/1?pretty'&#xA;</code></pre>&#xA;&#xA;<p>I get:</p>&#xA;&#xA;<pre><code>{&#xA;"_index" : "website",&#xA;"_type" : "blog",&#xA;"_id" : "1",&#xA;"_version" : 15,&#xA;"found" : true,&#xA;"_source":{"title":"My first blog entry","text":"foo","tags":["testing 1"],"views":43}&#xA;}&#xA;</code></pre>&#xA;&#xA;<p>2) perform _bulk:</p>&#xA;&#xA;<pre><code>curl -XPOST localhost:9200/_bulk --data-binary '&#xA;{"delete": { "_index": "website", "_type": "blog", "_id": "1" }}\n&#xA;{ "create": { "_index": "website", "_type": "blog", "_id": "1" }}\n&#xA;{ "title": "My first blog entry" }\n'&#xA;</code></pre>&#xA;&#xA;<p>I get:</p>&#xA;&#xA;<pre><code>{"error":"ActionRequestValidationException[Validation Failed: 1: no requests added;]",&#xA; "status":400}&#xA;</code></pre>&#xA;&#xA;<p>Why is that?</p>&#xA;&#xA;<p>Thanks in advance).</p>&#xA;